### ISSUE TITLE
mappo and mappo_ns dont run

### ISSUE THREAD

**Issue by at-peter** [uoe-agents/epymarl#1]
Hey y'all, 

I'm trying to replicate your results from you paper but am unfamiliar with torch. I encountered an error when trying to run mappo and mappo_ns: 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat1 in method wrapper_addmm)

I have tested all the other algorithms and none of them have this error. I was wondering if you have encountered this error before and know of a way to force all the tensors to either go to the CPU or the GPU (preferably).  

The system that I am running has a GPU with CUDA 11.4 and CuDNN 8.2 and is running Windows 10. 

thanks for your attention, 

Peter

**Comment by semitable** [comment]
Hi @at-peter 
Thank you for spotting this. We believe this has been resolved with commit a16fd23b2fc9c1b76953375a36108149377d5468. Let us know if the issue persists for you.
