### ISSUE TITLE
Why batch reward standarization works?

### ISSUE THREAD

**Issue by to1a** [uoe-agents/epymarl#10]
Hello again, and this time I have another question about batch reward standarization: why it works?
`        if self.args.standardise_rewards:
            rewards = (rewards - rewards.mean()) / (rewards.std() + 1e-5)`
This normalizes rewards per batch sampled from the buffer. But if an episode is sampled by different batches, the normalized rewards of that episode will be different(for different episodes sampled by different policies are not i.i.d.). I think it would break the reward of the environment and cause some instability, but it indeed improves the performance of my MARL algorithms. So could you give me more explanations on why using batch reward standarization and why it works? Thanks!

**Comment by papoudakis** [comment]
Hello,
we found that reward standardisation works quite well in practice. We believe that the batch has a good approximation of the reward's mean and std. Additionally, using the reward standardisation is just a hyperparameter that we tuned. For all combinations of algorithms and environments, we executed the algorithms both with and without reward standardisation. And we present results for the hyperparameter combinations that achieve the highest returns.
