### ISSUE TITLE
Implementation tricks for different algorithms

### ISSUE THREAD

**Issue by waterhorse1** [uoe-agents/epymarl#11]
It's a really Nice work on benchmarking multi-agent RL algorithms and I really like it. When I go through the code, I find out epymarl basically only implements the basic version of different algorithms and ignore many different implementation tricks for different algorithms, such as the value normalization trick for MAPPO mentioned in [MAPPO](https://arxiv.org/pdf/2103.01955.pdf) , or the value clipping trick for IPPO mentioned in [IPPO](https://arxiv.org/abs/2011.09533). Will furture version epymarl support such tricks?

**Comment by papoudakis** [comment]
Hello, 
we aim to add more implementation details of different algorithms in the future. The basic idea was for all algorithms to have very similar implementations to be able to better compare their achieved returns. We are also happy to accept pull requests for these implementation tricks.

**Comment by waterhorse1** [comment]
Thank you for your answer.
