### ISSUE TITLE
GPU usage without run.sh

### ISSUE THREAD

**Issue by AlRodA92** [uoe-agents/epymarl#13]
Hi,

Because I have some problems in running an experiment using the bash run.sh command, could you please let me know if the standar running command `python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z`automatically check if there are somo GPU device and then use that GPU to running the experiment?? 

I check in real time the GPU usage and it is true that the % of usage is changing from 7% to 40%, so I don't know if the fact that it is not 100% used is due to some problem of mine of it is the way the code is design.

Thanks!

**Comment by papoudakis** [comment]
Hi,
using GPUs in RL does not always speed up the training. There are two main reasons behind this:
1. Usually, the network and the batch size is relatively small (compared to other applications of DL).
2. The environment is running in the CPU and as a result there is a high overhead from transferring data between the CPU and the GPU. 
As a result, it is not unexpected that your GPU usage is not close to 100.
If you want to stop using the GPU, you just need to set the flag `use_cuda: False` in the `default.yaml` file

**Comment by AlRodA92** [comment]
> 
Yes, I compared usign a virtual machine with 8 Cpu's with other VM with the same number of VM and a K80 GPU and the last ones is slower. Thanks for the fast response!
