### ISSUE TITLE
Number of Evaluations between Off-Policy and On-Policy

### ISSUE THREAD

**Issue by AlRodA92** [uoe-agents/epymarl#15]
Hi,

I have some doubts about the number of evaluations between off-policy and on-policy algorithms. In the paper is explained that:

_To account for the improved sample efficiency of off-policy over on-policy algorithms and to allow for fair comparisons, we train off-policy algorithms for two million steps and on-policy algorithms for 20 million steps. We evaluate off-policy algorithms every 50,000 steps and on-policy algorithms every 500,000 steps. As a result, a total of 40 evaluations are executed during the training of each algorithm_

But with the code as it is in the repository but changing the t_max to 2M and 20M at QMIX and MAPPO respectively I get 41 **test_return_mean** in QMIX and 401. So I do not really know I have to change other parameter or the numbers are corrected.

Thanks

**Comment by papoudakis** [comment]
Hi, 
you should change the evaluation frequency (the `test_interval` variable) in the `gymma.yaml` and the `sc2.yaml` files to 500,000.
Best regards,
Georgios

**Comment by AlRodA92** [comment]
> Hi, you should change the evaluation frequency (the `test_interval` variable) in the `gymma.yaml` and the `sc2.yaml` files to 500,000. Best regards, Georgios

Thanks a lot!
