### ISSUE TITLE
Did you try to use the true global state as input in LBF?

### ISSUE THREAD

**Issue by GoingMyWay** [uoe-agents/epymarl#16]
Dear Authors,

To train QMIX on LBF, I found it uses the concatenated obs as the states. For fully observable settings, there is no problem doing so. I am curious about did you try to use the true global state as input in LBF? Is the performance good? 

Thank you in advance.

**Comment by semitable** [comment]
Hi @GoingMyWay 
Do you mean extracting a global state from the partially observable versions of LBF?
No, we only looked into concatenating the observations, which are just an approximation of the global state (in the partially observable environments). There should be no change in the fully-observable ones.

**Comment by GoingMyWay** [comment]
Thanks for the clarification.
