### ISSUE TITLE
Evaluate results question

### ISSUE THREAD

**Issue by AlRodA92** [uoe-agents/epymarl#20]
Hi, 

I have a question about the evaluation of a model. I use the code as described

`python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=Multi_task_6m1M_vs_12m1M checkpoint_path=results/models/qmix_best/ save_replay=True test_nepisode=5 evaluate=True'

So, I run the model for evualuation 5 episodes but the resulst with the return_mean and the other metric have only one value

![image](https://user-images.githubusercontent.com/83612075/164519129-1d5166a2-817a-4264-a275-8c5a9f1c24d0.png)

I try some modifications on the config but I get the same results. 

What I try to do is obtain the same number of results that the number of episodes. That is to say, the return and the other metric obtained on each of the episodes.

Thanks!

**Comment by semitable** [comment]
I believe this is the mean and std of the evaluation, not the individual runs. This is implied in the name of the metrics: `test_reward_survive_mean` and `..._std`. Is that what you mean?

**Comment by AlRodA92** [comment]
> I believe this is the mean and std of the evaluation, not the individual runs. This is implied in the name of the metrics: `test_reward_survive_mean` and `..._std`. Is that what you mean?

Sorry for the delay. Yeah, the values are the mean and the std of the returns, but if you have only one episode and therefore only one return the mean is the return itself. What I wanted is that if I run a X number of test in evaluation mode, the program gives me a X number of returns and metrics, one for each episode, not the mean of all of them in one single value. I check the code and the "problem is the code lines marked in red in the following figure.

![código_test](https://user-images.githubusercontent.com/83612075/165697567-afbf2630-3eb0-464a-beb0-7a8df805d573.png)

Even in test mode if I set the test_nepisodes = 100 for example the code gives me the mean of the returns of all 100 episodes. If you only check if test_mode is True and erase the second condition the code give me what I want, that 100 returns and metric. So I add another elif condition for that task.

Thanks for the quick response by the way!

I close the issue.
