### ISSUE TITLE
Training slows down

### ISSUE THREAD

**Issue by GoingMyWay** [uoe-agents/epymarl#25]
Hi, I am using epymarl to train melting pot,  I replaced the rnn+mlp network with rnn+cnn. I found in IPPO and IA2C that the time cost for [learning each batch](https://github.com/uoe-agents/epymarl/blob/main/src/run.py#L198) increases over time shown below. I tried my best to debug it and I found it very hard to find the reason. I even used `th.cuda.empty_cache()` and `th.cuda.synchronize(device=th.device("cuda"))` but no help. The following figure shows the average time cost of the past 10 updates.

![Avg time cost of the past 10 updates](https://user-images.githubusercontent.com/9346460/176718893-b3539546-9e0b-4816-a3ce-f7a1a51ab1a2.png)

Did you find also found such an issue?

**Comment by papoudakis** [comment]
Do the batch dimensions change through time??
For example, what is the time dimension of the batch at the first update and what is the time dimension of the batch after 30M steps?

**Comment by GoingMyWay** [comment]
> Do the batch dimensions change through time?? For example, what is the time dimension of the batch at the first update and what is the time dimension of the batch after 30M steps?

Hi, the batch did not change over time. The time dimension in my case is 51, and the batch size is 60.

**Comment by GoingMyWay** [comment]
I guess maybe the other components introduced by me raised the issue. With vanilla epymarl, the time cost per update on Foraging-2s-8x8-2p-2f-coop-v2 trained with IPPO did not increase over time as shown below. I am closing this issue.


![image](https://user-images.githubusercontent.com/9346460/176858864-c7598ef6-8b42-44d9-9eeb-c7b1cef295a7.png)

**Comment by GoingMyWay** [comment]
Hi, this is an issue of sacred, https://github.com/IDSIA/sacred/issues/877
