### ISSUE TITLE
Cannot obtain the reported results on MPE:SimpleSpread task

### ISSUE THREAD

**Issue by LINGYUNFDU** [uoe-agents/epymarl#29]
Hi,

Thanks for the great code! However, when I run the given command to train MPE:SimpleSpread task, it seems the converged performance is far from the results on the paper. For example, the average return using QMIX, MADDPG are around -500, -400, and random policy is around -700. The number from the paper is around -120. 

Could you tell me what is the possible problem?

Thanks!

**Comment by papoudakis** [comment]
Hi,

the returns that are presented in the paper for the MPE tasks are divided by the number of agents.
