### ISSUE TITLE
TypeError: 'Box' object is not iterable, WHY?

### ISSUE THREAD

**Issue by SaraRezaei** [uoe-agents/epymarl#36]
Hi,
I used those lines in my custom environment:
        self.observation_space = gym.spaces.Box(np.array([0,0,0,0,0,0,0,0,0,0]), np.array([9,9,9,9,9,9,9,9,9,9]), shape=(10,), dtype=np.int64)
        self.action_space = gym.spaces.Box(low=0, high=9, shape=(1,), dtype=np.int64)

but I received this error:
      .....\epymarl-main\src\envs\__init__.py", line 56, in __init__
          for sa_obs in env.observation_space:
      TypeError: 'Box' object is not iterable
 
thank you

**Comment by lucascamaradb** [comment]
EPyMARL expects the observation and action spaces of each agent to be within tuples with length equal to the number of agents. So you should have something like this:
```
N_agents = 10
self.action_space = gym.spaces.Tuple(tuple( [gym.spaces.Box(low=0, high=9, shape=(1,), dtype=np.int64]*N_agents ))
```
Btw, you should also consider using `gym.spaces.Discrete` instead of Box.

**Comment by SaraRezaei** [comment]
that's right!
It's works.
:)
