### ISSUE TITLE
repeated matrix game

### ISSUE THREAD

**Issue by LINGYUNFDU** [uoe-agents/epymarl#37]
Hi, thanks for the contribution to the community!

I didn't find the environments of repeated matrix games. Although they are simple and may be created by users, it would be great if we can use them directly from this repo since the results from the paper show the suboptimal performance of many algorithms. Thus, I think these matrix games are worth a try.

**Comment by papoudakis** [comment]
We used this repo:
https://github.com/semitable/matrix-games

**Comment by LINGYUNFDU** [comment]
Thanks very much!
