### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by LLLLLH76** [uoe-agents/epymarl#4]
May I ask which version of python should we use?

**Comment by papoudakis** [comment]
Hi
Any version of Python >= 3.7.

**Comment by LLLLLH76** [comment]
Thank you!



---Original---
From: "Giorgos ***@***.***&gt;
Date: Mon, Sep 6, 2021 20:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [uoe-agents/epymarl] python version (#4)




 
Hi
 Any version of Python &gt;= 3.7.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
