### ISSUE TITLE
Unable to install requirements.txt

### ISSUE THREAD

**Issue by xylhal** [uoe-agents/epymarl#53]
Hello

I have a clean conda environment with python 3.9 and I am getting the following error. Any pointers on how to resolve this?

Also, are there any future plans to make this repo compatible with gymnasium?
```
Collecting gym==0.21.0 (from -r requirements.txt (line 3))
  Using cached gym-0.21.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by WvterLust** [comment]
If you are running on Mac, the problem might be with 'Xcode' / 'SetupTools'. I had the problem recently too. The solution appears to be to use:
pip3.4 install --upgrade setuptools.
And then proceed with installing requirements.txt 

If you have Xcode installed you may need to downgrade and only use SetupTools instead.

Here's a link from a similar issue and where the solution was found.
https://github.com/giampaolo/psutil/issues/1268

Hope this helps!

**Comment by whoisvicky** [comment]
I also came across the issue of Mapping which has been removed from Pyhton 3.9. How to fix it?

**Comment by WvterLust** [comment]
Easiest solution I found was downgrading to python 3.8.16 and it should work

**Comment by xylhal** [comment]
> If you are running on Mac, the problem might be with 'Xcode' / 'SetupTools'. I had the problem recently too. The solution appears to be to use: pip3.4 install --upgrade setuptools. And then proceed with installing requirements.txt
> 
> If you have Xcode installed you may need to downgrade and only use SetupTools instead.
> 
> Here's a link from a similar issue and where the solution was found. [giampaolo/psutil#1268](https://github.com/giampaolo/psutil/issues/1268)
> 
> Hope this helps!

Thanks, will try it out and see how it goes

**Comment by LukasSchaefer** [comment]
Hi!

Sorry for the very late response. Installing `gym==0.21` became increasingly difficult since the library is quite old and no longer maintained. Given these difficulties, we worked on and just published a big update to EPyMARL including lots of new features including a move to the maintained `gymnasium` library in replacement of `gym` (as well as training in non-common-reward games, weights and biases logging and more). You can find out more details in the readme.

I hope this clarifies your issue! I will close this issue, let us know if you have any outstanding issues.
