### ISSUE TITLE
Hi, why NonSharedMAC only has one agent? thanks

### ISSUE THREAD

**Issue by restart-again** [uoe-agents/epymarl#58]
Hi, thanks for your wonderful sharing. I am wondering if we don't share paremeters, there should be mult-agents, but in your classe NonSharedMAC definition, there is only one agent exactly like the case of sharing paremeters? please help me to understand better, thanks.
BTW, ia2c is not working if I set mac to non_shared_mac with Foraging-8x8-2p-3f-v2 env.

**Comment by LukasSchaefer** [comment]
Hi!

Sorry for the very late response.

For the controller without parameter sharing, we use this controller alongside the [non-shared agent definition](https://github.com/uoe-agents/epymarl/blob/main/src/modules/agents/rnn_ns_agent.py#L13) which initialises one network for each agent.

If you want to use non-shared setups, you should use the `ia2c_ns` config which specifies the non-shared controller as well as the non-shared critic and agent definition as you can see in the [respective config](https://github.com/uoe-agents/epymarl/blob/main/src/config/algs/ia2c_ns.yaml). Those should always be used together.

I hope this clarifies your issue! I will close this issue, let us know if you have any outstanding issues.

On a sidenote, we just published a big update to EPyMARL including lots of new features (including training in non-common-reward games, move to gymnasium from deprecated gym, weights and biases logging) -- you can find more details in the readme!
