### ISSUE TITLE
Paper of MAA2C

### ISSUE THREAD

**Issue by Ynjxsjmh** [uoe-agents/epymarl#6]
I' reading the version on https://arxiv.org/pdf/2006.07869.pdf, the first time the term `MAA2C` appears is in the following paragraph

![image](https://user-images.githubusercontent.com/40143136/135022757-05a56041-aca4-4615-83d8-70904d7586eb.png)

But I didn't see the cited paper of MAA2C.

**Comment by semitable** [comment]
Hi @Ynjxsjmh 

MAA2C is just our implementation of A2C with a centralised critic (centralised critic as described in the relevant section).
We are not aware of a publication that specifically describes this, and perhaps it's only used as a baseline in other papers.
