### ISSUE TITLE
SMACv2 and SMAC Lite

### ISSUE THREAD

**Issue by rfali** [uoe-agents/epymarl#66]
Does the current repo support SMAC v2 out of the box, and if not, is that something that is being contemplated? 

If you can also comment on the availability of SMAC Lite with this repo. 

Thanks

**Comment by LukasSchaefer** [comment]
Hi!

Thanks a lot for raising this. We just published a big update to EPyMARL including lots of new features (including training in non-common-reward games, move to gymnasium from deprecated gym, weights and biases logging). One of those features is a new integration of SMACv2 out-of-the-box (with a new wrapper) as well as integration of SMAClite! Please see the documentation for details, but I will close this issue for now. Let us know if there are any outstanding issues for this :)
