### ISSUE TITLE
[BUG] Duplicate agent_grad_norm in maddpg_learner.py Needs Removal

### ISSUE THREAD

**Issue by wmn7** [uoe-agents/epymarl#67]
Hello Maintainer,

I've noticed a duplicate `agent_grad_norm` in the `maddpg_learner.py` file that appears to be redundant and should be removed. The duplication can be found in the following lines:

https://github.com/uoe-agents/epymarl/blob/4b743a8e038e5e6953b018d99ca00c07e612a2f0/src/learners/maddpg_learner.py#L136-L146

Additionally, I saw that there has been a pull request submitted which addresses this issue: https://github.com/uoe-agents/epymarl/pull/60

Best regards,
Maonan Wang

**Comment by LukasSchaefer** [comment]
Hi, thanks for raising this issue! This has now been resolved in the recent PR :)
