### ISSUE TITLE
Bugs Finding in action_selector.py

### ISSUE THREAD

**Issue by W-Zhi-Chao** [uoe-agents/epymarl#75]
I think there're some problems with the soft policy selector, since the code does not use argument 'test_mode' in the 'select_action' function.

**Comment by LukasSchaefer** [comment]
That is not a bug. Please note that algorithms such as A2C and PPO learn parameterised policies and always follow a stochastic policy that samples from such policy so the policy that is being followed is identical during training (`test_mode=False`) and evaluation (`test_mode=True`).

This is in contrast to e.g. an $\epsilon$-greedy policy that typically executes a greedy policy during evaluation (`test_mode=True`) and a highly random policy depending on the value of `\epsilon` during training (`test_mode=False`).

I'll close this issue but let me know if anything is unclear and you still believe there is a problem!
